description: gendata

env_defaults:
  SKU: 10C3
  TARGET: msrresrchvc
  SLA: premium

environment:
  image: amlt-sing/acpt-torch2.4.1-py3.10-cuda12.4-ubuntu22.04

  setup:
    - git clone https://github.com/zhangmiaosen2000/cccrawl.git
    - cd cccrawl
    - bash install.sh
storage:
  lmm:
    container_name: vground
    mount_dir: /mnt/vground
    storage_account_name: t2vgusw2
    is_output: True


target:
  service: sing
  workspace_name: t2vgws2
  name: ${TARGET}

jobs:
  - name: split_0_2to3
    process_count_per_node: 1
    execution_mode: Basic
    priority: High          # [High, Medium, Low]. On AMLK8s, the priority value is mapped to 200, 100, and 80, respectively.
    sla_tier: ${SLA}       # [premium, standard, basic]
    identity: managed
    
    sku: ${SKU}
    command:
      - cd cccrawl
      - python gendata_main.py --index /mnt/vground/selected_url_from_domain/CCurls_sampled_50pd_split_0.json --out-dir /mnt/vground/CCCrawl_Raw --run-name split_0_2to3 --start 2 --end 3
  
  - name: split_0_3to4
    process_count_per_node: 1
    execution_mode: Basic
    priority: High          # [High, Medium, Low]. On AMLK8s, the priority value is mapped to 200, 100, and 80, respectively.
    sla_tier: ${SLA}       # [premium, standard, basic]
    identity: managed
    
    sku: ${SKU}
    command:
      - cd cccrawl
      - python gendata_main.py --index /mnt/vground/selected_url_from_domain/CCurls_sampled_50pd_split_0.json --out-dir /mnt/vground/CCCrawl_Raw --run-name split_0_3to4 --start 3 --end 4
  